apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
spec:
  selector:
    matchLabels:
      app: service
  replicas: 1
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service
          image: service:placeholder_name
          imagePullPolicy: Always
          env:
            - name: MONGO_DB_URL
              value: mongodb://database-0.database-svc.mongodb.svc.cluster.local:27017,database-1.database-svc.mongodb.svc.cluster.local:27017,database-2.database-svc.mongodb.svc.cluster.local:27017/?replicaSet=database
              # single node connection string seems to work fine, too
              # value: mongodb://database-0.database-svc.mongodb.svc.cluster.local:27017?replicaSet=database
          readinessProbe:
            httpGet:
              path: /
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3333
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: service
  ports:
    - name: http
      port: 3333
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: service-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
